sudo: required

env:
  - DOCKER_COMPOSE_VERSION: 1.8.0
 
services:
  - docker

before_install:
  - sudo apt-get update -y
  - sudo apt-get install vim curl
  - mkdir gitlab
  - curl -o gitlab/docker-compose.yml https://raw.githubusercontent.com/sameersbn/docker-gitlab/master/docker-compose.yml
  - (cd gitlab; docker-compose up -d)

script:
  - ls
  - curl --user "root" --request POST --data '{"grant_type": "password", "username": "root", "password": "5iveL!fe"}' http://localhost:10080//oauth/token
  - pwd

