sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - mkdir gitlab
  - curl -o gitlab/docker-compose.yml https://raw.githubusercontent.com/sameersbn/docker-gitlab/master/docker-compose.yml
  - (cd gitlab; docker-compose up -d)

script:
  - ls
